### ISSUE TITLE
DQL error in MediaKeyworkRepository:topKeyWord()

### ISSUE THREAD

**Issue by Garcia6l20** [ariescdi/documentio#43]
``` SQL
An exception occurred while executing 'SELECT d0_.word AS word0, COUNT(d1_.id) AS sclr1 FROM dio_mediakeyword d0_ INNER JOIN dio_mediakeywords_media d2_ ON d0_.id = d2_.keyword_id INNER JOIN dio_media d1_ ON d1_.id = d2_.media_id GROUP BY d1_.id ORDER BY sclr1 DESC LIMIT 10':

SQLSTATE[42803]: Grouping error: 7 ERROR: column "d0_.word" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: SELECT d0_.word AS word0, COUNT(d1_.id) AS sclr1 FROM dio_me...
```

It seems we must add the word in the group by clause ... not sure.

Im on it ..

**Comment by valeriangalliat** [comment]
This is because this query mixes an aggregation function (`COUNT`) and a raw field (`word`). Some engines will refuse to execute this because it makes no sense.

Though, I don't get why `COUNT(id)` is used in combination with `GROUP BY id`. There is no point doing this if `id` is unique… `COUNT(id)` would always resolve to `1`. What is this query trying to do? Where is it in the source?

**Comment by Garcia6l20** [comment]
Yep cf.: Title (MediaKeyworkRepository:topKeyWord)

https://github.com/ariescdi/documentio/blob/develop/src/MediaBundle/Entity/MediaKeywordRepository.php

**Comment by Garcia6l20** [comment]
I solved it, but I want to test it and I dont know the way we add a media from know.

Help ...

**Comment by Garcia6l20** [comment]
``` SQL
            SELECT k.word, COUNT(m) AS compteur
            FROM MediaBundle:MediaKeyword k
            JOIN k.medias m
            GROUP BY m.id, k.word
            ORDER BY compteur DESC
```
